config/routes.rb
Rails.application.routes.draw do
  
  resources :schedules do
    collection {
      post :import
      post :export
      post :delete
    }
    member {
      get :minimize
    }
  end
  
  resources :performances do
    collection {
      put :sort
      post :remove
      post :lock
      post :revive
    }
  end

  root :to => redirect('/schedules')

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  helper ScheduleHelper
  
  def generate_conflict(perf1, perf2, intersect)
    if intersect.length() == 0
      return nil
    end
    
    return {:first_performance => perf1.name,
            :second_performance => perf2.name,
            :dancers => intersect
    }
  end

  def conflicts(act_number)
    # Go linearly through the schedule and mark conflicts
    conflict_list = []
    performances = @ordered_performances[act_number]
    
    performances.each_with_index do |perf, i|
      if i + 1 < performances.length()
        first_dance_list = perf.dances
        next_dance_list = performances[i + 1].dances
        intersect = helpers.intersect_by_dancer_id(first_dance_list, next_dance_list)
        conflict = generate_conflict(perf, performances[i+1], intersect)
        
        if conflict
          conflict_list.append(conflict)
          # Mark the first one to be the "conflicting" on for the view to catch
          @conflicting_performances.append(perf.id)
        end
      end
    end
    
    return conflict_list
  end
  
  def index
    @schedules = Schedule.all
  end

  # For importing a schedule from a CSV file in params
  def import
    case Schedule.check_csv(params[:file])
    when :no_file
      notice_msg = "No file selected"
    when :failed
      notice_msg = "Failed to Import Data!!!"

    when :success
      # On success, materialize the schedule with 2 acts, and send the data read
      # from the CSV file (by default, all performances in act 1)
      csv_data = Schedule.read_csv(params[:file])
      schedule = Schedule.create!(filename: params[:file].path, name: params[:schedule_name])
      Act.create!(number: 1, schedule_id: schedule.id)
      Act.create!(number: 2, schedule_id: schedule.id)
      schedule.import(csv_data)
      notice_msg = "Successfully Imported Data!!!"
      flash[:minimize] = true
      redirect_to edit_schedule_path(id: schedule.id), flash: {success: notice_msg}
      return
    end
    redirect_to schedules_path, flash: {notice: notice_msg}
  end
  
  def remove_unscheduled(performances)
    perfs = []
    performances.each do |perf|
      if perf.scheduled
        perfs.append(perf)
      end
    end
    return perfs
  end
  
  def form_schedule(gen_conflicts=false)
    @schedule.acts.each do |act|
      @ordered_performances[act.number] = remove_unscheduled(act.performances).sort_by { |perf| perf.position }
      @unscheduled_performances[act.number] = (act.performances - @ordered_performances[act.number])
          .sort_by { |perf| perf.position }
      if gen_conflicts
        @conflicts[act.number] = self.conflicts(act.number)
      end
      reindex(@ordered_performances[act.number])
    end
    flash[:conflicts] = @conflicts
    flash[:conflicting_performances] = @conflicting_performances
    puts @conflicting_performances.to_s
  end
  
  def init_schedule
    @ordered_performances = {}
    @conflicts = {}
    @conflicting_performances = []
    @unscheduled_performances = []
  end
  
  # Do the work of adjusting all the relative positions before and after
  # using the helper to minimize the conflicts
  def minimize_schedule
    helpers.minimize_conflicts(@schedule, @ordered_performances)
    form_schedule(true)
  end
  
  def reindex(performances)
    performances.each_with_index do |perf, i|
      perf.update(position: i+1)
    end
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
    if @schedule == nil
      redirect_to schedules_path, notice: "Schedule with id #{params[:id]} could not be found."
      return
    end
    
    init_schedule()
    form_schedule(flash[:minimize] == nil)
    
    if flash[:minimize]
      minimize_schedule()
    end
    
    @act_classes = {}
    @act_classes[1] = "floatLeftA"
    @act_classes[2] = "floatRightA"

    flash[:conflicts] = @conflicts
    flash[:conflicting_performances] = @conflicting_performances
  end


  def export
    @schedule = Schedule.find(params[:id])

    @ordered_performances = {}
    @schedule.acts.each do |act|
      @ordered_performances[act.number] = act.performances.sort_by do |perf|
        perf.position
      end
      @ordered_performances[act.number] = @ordered_performances[act.number].filter do |perf|
        perf.scheduled == true
      end
    end
    
    send_data Schedule.to_csv(@ordered_performances, flash[:conflicts], flash[:conflicting_performances]), filename: "#{@schedule.name}_exported_schedule.csv"
  end

  def minimize
    flash[:minimize] = true
    redirect_to edit_schedule_path(id: params[:id]), flash: {success: "New minimal schedule generated!"}
  end

  def delete
    schedule_id = params[:id]
    @schedule = Schedule.find(params[:id])
    if @schedule == nil
      redirect_to schedules_path, notice: "Schedule with id #{params[:id]} could not be found."
      return
    end
    
    # Each act is responsible for deleting data under it
    Schedule.remove_acts(schedule_id)
    Schedule.destroy(schedule_id.to_i)
    
    redirect_to root_path, flash: {success: "Successfully deleted schedule "+schedule_id.to_s}
  end
  
end

app/helpers/schedule_helper.rb
module ScheduleHelper  
  @@MAX_PERMS = 1000
  
  # Thank you https://medium.com/@daweiner16/factorial-using-ruby-app-academy-practice-problem-c1a179ac445f
  def factorial(n)
    if n == 0
      return 1
    else
      return n * factorial(n-1)
    end
  end
  
  def intersect_by_dancer_id(dances_a, dances_b)
    if dances_a.length() > dances_b.length()
      return intersect_by_dancer_id(dances_b, dances_a)
    end
    
    intersection = []
    dances_a.each do |a|
      dances_b.each do |b|
        if a.dancer_id == b.dancer_id
          intersection.append(Dancer.find(a.dancer_id).name)
        end
      end
    end
    
    return intersection
  end
  
  # Put all the performances in a schedule in one list
  def concatenate(act1_perfs, act2_perfs)
    all_perfs = []
    act1_perfs.each do |perf|
      all_perfs.append(perf)
    end
    num_act1_perfs = act1_perfs.length()
    act2_perfs.each do |perf|
      perf.position = perf.position + num_act1_perfs
      all_perfs.append(perf)
    end
    return all_perfs
  end
  
  # Adjust all the positions of dances after act 1 back to their
  # positions relative to only their act(s)
  def divide(first_act2)
    num_act1_perfs = @performances.select {|perf| perf.position < first_act2}.length
    
    @performances.each do |perf|
      if perf.position < first_act2
        perf.act = @schedule.acts[0]
        perf.save
      else
        perf.act = @schedule.acts[1]
        perf.position = perf.position - num_act1_perfs
        perf.save
      end
    end
    
    # Have to reload the schedule and fix up @ordered_performances
    [1,2].each do |idx|
      @ordered_performances[idx] = @performances.select {|p| p.act.number == idx }
                                          .sort_by {|p| p.position }
    end
    @schedule.reload
  end
  
  def form_graph
    @graph = {}
    @performances.each do |perf|
      this_performance_dances = perf.dances
      @performances.each do |other_perf|
        if perf.id < other_perf.id
          other_performance_dances = other_perf.dances
          intersection = intersect_by_dancer_id(this_performance_dances, 
                                                  other_performance_dances)
          if !@graph.keys.include? perf.id
            @graph[perf.id] = {}
          end
          
          @graph[perf.id][other_perf.id] = intersection
        end
      end
    end
  end
  
  # Returns the total cost (related to number of conflicts) in given schedule
  # order permutation)
  def score_perm(permutation)
    # First form the schedule
    temp_schedule = []
    permutation.each do |index|
      temp_schedule.append(@performances[index])
    end
    
    # Then score it
    first_index = 0
    second_index = 1
    curr_score = 0
    last_conflicts = []
    while second_index < temp_schedule.length()
      first_id = temp_schedule[first_index].id
      second_id = temp_schedule[second_index].id
      min_id = [first_id, second_id].min
      max_id = [first_id, second_id].max
      
      #if @performances[first_index].act_id == @performances[second_index].act_id
        curr_conflicts = @graph[min_id][max_id]
        curr_conflicts.each do |curr_conflict|
          if last_conflicts != nil and last_conflicts.include? curr_conflict
            curr_score += 2
          else
            curr_score += 1
          end
        end
      #else
      #  curr_conflicts = nil
      #end
      
      first_index += 1
      second_index += 1
      last_conflicts = curr_conflicts
    end
    return curr_score
  end
  
  # To avoid adding the same order twice
  def add_order(perms, original_order, new_order)
    while perms.include? new_order
      new_order = original_order.shuffle
    end
    perms.append(new_order)
    return perms
  end
  
  def permute(original_order, num_perms, excluded)
    perms = [original_order]
    if num_perms <= @@MAX_PERMS - 1 && 
          factorial(original_order.length()) <= @@MAX_PERMS - 1
      perms = original_order.permutation.to_a
    else
      (1..@@MAX_PERMS-1).to_a.each do
        # Find a new ordering
        new_order = original_order.shuffle
        perms = add_order(perms, original_order, new_order)
      end
    end
    
    if excluded.length > 0
      perms.each do |perm|
        #puts "perm before: " + perm.to_s + " Excludeds: " + excluded.to_s
        excluded.each do |excluded_index|
          perm.insert(excluded_index, excluded_index)
        end
        #puts "perm after: " + perm.to_s
      end
    end
    
    # Also need to check if the factorial exceeds the num_perms asked for
    
    return perms
  end
  
  def get_perms(performances)
    original_order = (0..performances.length() - 1).to_a
    
    excluded = []
    original_order.each do |index|
      if performances[index].locked
        excluded.append(index)
      end
    end
    
    factorial_value = factorial(performances.length())

    if factorial_value > @@MAX_PERMS
      num_perms = @@MAX_PERMS - 1
    else
      num_perms = factorial_value
    end
    
    return permute(original_order - excluded, num_perms, excluded)
  end
  
  def find_min_perm(perms)
    min_score = score_perm(perms[0])
    min_idx = 0
    perms.each_with_index do |perm, i|
      score = score_perm(perm)
      #puts "score " + score.to_s
      if score < min_score
        min_score = score
        min_idx = i
      end
    end
    
    puts "Min score is " + min_score.to_s + " to perm " + perms[min_idx].to_s
    
    return perms[min_idx]
  end
  
  # Both update the positions of all perfs and reorder (at the end)
  def reorder_performances(winner_permutation)
    curr_pos = 1
    winner_permutation.each do |winner_index|
      perf = @performances[winner_index]
      perf.update(position: curr_pos)
      curr_pos += 1
    end
    @performances.sort_by! {|p| p.position }
  end
  
  # Takes a list of performances (AR object references) and attempts
  # to minimize the conflicts between them (changes the position field
  # of each performance- no need to return)
  def minimize_conflicts(schedule, ordered_performances)
    @schedule = schedule
    @ordered_performances = ordered_performances
    @performances = concatenate(@ordered_performances[1], 
                                @ordered_performances[2])
                                
    original_act2_start = @ordered_performances[1].length
    
    form_graph
    perms = get_perms(@performances)
    winner_permutation = find_min_perm(perms)
    reorder_performances(winner_permutation)
    
    divide(original_act2_start + 1) # The performance positions back into 2 acts
    
    return @ordered_performances
  end
end

app/views/schedules/edit.html.haml
-#  This file is app/views/movies/schedules.html.haml
-#%link(rel="stylesheet" href="assets/stylesheets/button.css" crossorigin="anonymous")
-#= javascript_include_tag 'application', 'data-turbolinks-track' => true

%h3= "Use this page to edit your schedule!"

%div.text-center
  %div= button_to "Regenerate", minimize_schedule_path(@schedule.id), method: "get", class: "header btn btn-success"

- @schedule.acts.each do |act|
  %div{:class => "#{@act_classes[act.number]}"}
    %table{:id => "act"+act.number.to_s}
      %thead
        %tr.actHeader
          %th= "Act #{act.number}"
        %tr
          %td
      - unless @ordered_performances[act.number].empty?
        %tbody{:class => "sortable", "data-url" => sort_performances_path(:act_id => act.id)}
          - @ordered_performances[act.number].each do |perf|
            - unless perf.scheduled == false
              %tr{:id => dom_id(perf)}
                %td.actFormat{:id => dom_id(perf)}
                  %div.floatLeft
                    = perf.name
                  %div.floatRight
                    %div.floatLeftButton
                      - unless perf.locked == true
                        = button_to lock_performances_path, :id => "lock" + perf.name.to_s.gsub(" ", "_"), 
                              :class => "lock" + perf.name.to_s.gsub(" ", "_") do
                          = hidden_field_tag :performance_id, perf.id
                          = hidden_field_tag :schedule_id, act.schedule_id
                          = hidden_field_tag :locked, false
                          = image_submit_tag("unlock.jpg", alt: "Unlocked")
                      - else
                        = button_to lock_performances_path, :id => "lock" + perf.name.to_s.gsub(" ", "_"), 
                              :class => "lock" + perf.name.to_s.gsub(" ", "_") do
                          = hidden_field_tag :performance_id, perf.id
                          = hidden_field_tag :schedule_id, act.schedule_id
                          = hidden_field_tag :locked, true
                          = image_submit_tag("lock.png", alt: "Locked")
                    %div.floatRightButton
                      = button_to remove_performances_path, :id => "remove" + perf.name.to_s.gsub(" ", "_"), 
                            :class => "remove" + perf.name.to_s.gsub(" ", "_") do
                        = hidden_field_tag :performance_id, perf.id
                        = hidden_field_tag :schedule_id, act.schedule_id
                        = hidden_field_tag :scheduled, true
                        = image_submit_tag("x.png", alt: "Remove")
              - if @conflicting_performances.include? perf.id
                %tr{:class => "unmoveable"}
                  %td{:class => "unmoveable"}
                  - @conflicts[act.number].each do |conflict|
                    - if conflict[:first_performance] == perf.name
                      %td{:class => "alert alert-danger unmoveable"}
                        - conflict[:dancers].each do |dancer_name|
                          %div= dancer_name
      - else
        %tbody{:class => "droppable", "data-url" => sort_performances_path(:act_id => act.id)}
          %td.actFormat{:class => "unmoveable"}
            %em [ This act is empty. Dragging a performance here will move it into this act. ]
    %div.center{:id =>"act#{act.number}insert"}  
      = form_tag performances_path do
        = text_field_tag :new_performance_name, nil
        = hidden_field_tag :act_id, act.id
        = hidden_field_tag :position, @ordered_performances[act.number].length
        = hidden_field_tag :schedule, false
        = hidden_field_tag :locked, false
        = hidden_field_tag :schedule_id, act.schedule_id
        = submit_tag "Insert Dance into Act#{act.number}"        
    %div.left{:class => "sortableUnscheduled", "data-url" => sort_performances_path(:act_id => act.id)}
      %table
        %tbody
        - @unscheduled_performances[act.number].each do |perf|
          - unless perf.scheduled == true
            %tr{:id => dom_id(perf)}
              %td.actFormat{:id => dom_id(perf)}
                %div.floatLeft
                  = perf.name
                %div.floatRight
                  %div.floatRightButton
                  = button_to revive_performances_path, :id => "revive" + perf.name.to_s.gsub(" ", "_"), :class => "revive" + perf.name.to_s.gsub(" ", "_") do
                    = hidden_field_tag :performance_id, perf.id
                    = hidden_field_tag :schedule_id, act.schedule_id
                    = hidden_field_tag :scheduled, true
                    = hidden_field_tag :position, @ordered_performances[act.number].length + 1
                    = submit_tag("+")


%div
  %div.floatLeft
    = button_to delete_schedules_path, class: "btn btn-danger" do
      = hidden_field_tag :id, @schedule.id
      = "Delete Schedule"
  %div.floatRight
    = button_to "Export Schedule to CSV", export_schedules_path, :params => {"id" => @schedule.id }, :id => "export", :method => :post, class: "footer btn btn-primary"

app/views/schedules/index.html.haml
-#  This file is app/views/movies/index.html.haml

- if @schedules.empty?
  %h3 
  %h3= "Looks like you don't have any schedules yet!"
  %h3= "Click the button to upload your first one!"
- else
  %h3= "Schedules"
  - @schedules.each do |schedule|
    = link_to schedule.name, edit_schedule_path(id: schedule.id)

= form_tag import_schedules_path, multipart: true do
  %h5= "Choose a file: "
  = file_field_tag :file
  %h5= "Name: "
  = text_field_tag :schedule_name, nil, placeholder: 'Enter a name...'
  = submit_tag "Import from file"